import { Component, Input } from '@angular/core';
import {
  mdiAccount, mdiAccountOutline,
  mdiAccountBox, mdiAccountBoxOutline,
  mdiAccountMultiple, mdiAccountMultipleOutline,
  mdiAccountMultiplePlus, mdiAccountMultiplePlusOutline,
  mdiAccountPlus, mdiAccountPlusOutline,
  mdiAccountSearch, mdiAccountSearchOutline,
  mdiAlert, mdiAlertOutline,
  mdiAlertCircle, mdiAlertCircleOutline,
  mdiArrowDownBoldBox, mdiArrowDownBoldBoxOutline,
  mdiArrowUpBoldBox, mdiArrowUpBoldBoxOutline,
  mdiArrowLeftBoldBox, mdiArrowLeftBoldBoxOutline,
  mdiArrowRightBoldBox, mdiArrowRightBoldBoxOutline,
  mdiArrowDownBold, mdiArrowDownBoldOutline,
  mdiArrowUpBold, mdiArrowUpBoldOutline,
  mdiArrowLeftBold, mdiArrowLeftBoldOutline,
  mdiArrowRightBold, mdiArrowRightBoldOutline,
  mdiBookmark, mdiBookmarkOutline,
  mdiBookmarkOff, mdiBookmarkOffOutline,
  mdiBriefcase, mdiBriefcaseOutline,
  mdiCards, mdiCardsOutline,
  mdiCart, mdiCartOutline,
  mdiCheckCircle, mdiCheckCircleOutline,
  mdiCheck, mdiCheckOutline,
  mdiBallot, mdiBallotOutline,
  mdiBatteryCharging100, mdiBatteryChargingOutline,
  mdiClipboard, mdiClipboardOutline,
  mdiClipboardCheckOutline, mdiClipboardCheck,
  mdiClipboardPulse, mdiClipboardPulseOutline,
  mdiClock, mdiClockOutline,
  mdiClockAlert, mdiClockAlertOutline,
  mdiClose, mdiCloseOutline,
  mdiCloud, mdiCloudOutline,
  mdiCloudSearch, mdiCloudSearchOutline,
  mdiCoffee, mdiCoffeeOutline,
  mdiComment, mdiCommentOutline,
  mdiCommentAlert, mdiCommentAlertOutline,
  mdiCommentAccount, mdiCommentAccountOutline,
  mdiCommentMultiple, mdiCommentMultipleOutline,
  mdiContentSave, mdiContentSaveOutline,
  mdiEmail, mdiEmailOutline,
  mdiEmailOpen, mdiEmailOpenOutline,
  mdiEmailSearch, mdiEmailSearchOutline,
  mdiEye, mdiEyeOutline,
  mdiEyeOff, mdiEyeOffOutline,
  mdiFile, mdiFileOutline,
  mdiFilter, mdiFilterOutline,
  mdiFlag, mdiFlagOutline,
  mdiEngine, mdiEngineOutline,
  mdiFlash, mdiFlashOutline,
  mdiFlask, mdiFlaskOutline,
  mdiFlaskEmpty, mdiFlaskEmptyOutline,
  mdiFlowerTulipOutline, mdiFlowerTulip,
  mdiFolder, mdiFolderOutline,
  mdiFolderSearch, mdiFolderSearchOutline,
  mdiForum, mdiForumOutline,
  mdiHeart, mdiHeartOutline,
  mdiHome, mdiHomeOutline,
  mdiKeyboard, mdiKeyboardOutline,
  mdiLayers, mdiLayersOutline,
  mdiImage, mdiImageOutline,
  mdiInformation, mdiInformationOutline,
  mdiLightbulb, mdiLightbulbOutline,
  mdiLock, mdiLockOutline,
  mdiLockOpen, mdiLockOpenOutline,
  mdiMagnifyPlus, mdiMagnifyPlusOutline,
  mdiMagnifyMinus, mdiMagnifyMinusOutline,
  mdiMapMarker, mdiMapMarkerOutline,
  mdiMap, mdiMapOutline,
  mdiMapSearch, mdiMapSearchOutline,
  mdiMicrophone, mdiMicrophoneOutline,
  mdiNote, mdiNoteOutline,
  mdiPin, mdiPinOutline
} from '@mdi/js'

@Component({
  selector: 'mdi-home-page',
  templateUrl: './homePage.component.html',
  styleUrls: ['./homePage.component.scss']
})
export class HomePageComponent {
  title: string = 'Home';
  icons: regularOutline[] = [
    { regular: mdiAccount, outline: mdiAccountOutline },
    { regular: mdiAccountBox, outline: mdiAccountBoxOutline },
    { regular: mdiAccountMultiple, outline: mdiAccountMultipleOutline },
    { regular: mdiAccountMultiplePlus, outline: mdiAccountMultiplePlusOutline },
    { regular: mdiAccountPlus, outline: mdiAccountPlusOutline },
    { regular: mdiAccountSearch, outline: mdiAccountSearchOutline },
    { regular: mdiAlertCircle, outline: mdiAlertCircleOutline },
    { regular: mdiAlert, outline: mdiAlertOutline },
    { regular: mdiArrowDownBoldBox, outline: mdiArrowDownBoldBoxOutline },
    { regular: mdiArrowUpBoldBox, outline: mdiArrowUpBoldBoxOutline },
    { regular: mdiArrowLeftBoldBox, outline: mdiArrowLeftBoldBoxOutline },
    { regular: mdiArrowRightBoldBox, outline: mdiArrowRightBoldBoxOutline },
    { regular: mdiArrowDownBold, outline: mdiArrowDownBoldOutline },
    { regular: mdiArrowUpBold, outline: mdiArrowUpBoldOutline },
    { regular: mdiArrowLeftBold, outline: mdiArrowLeftBoldOutline },
    { regular: mdiArrowRightBold, outline: mdiArrowRightBoldOutline },
    { regular: mdiBookmark, outline: mdiBookmarkOutline },
    { regular: mdiBookmarkOff, outline: mdiBookmarkOffOutline },
    { regular: mdiBriefcase, outline: mdiBriefcaseOutline },
    { regular: mdiCards, outline: mdiCardsOutline },
    { regular: mdiCart, outline: mdiCartOutline },
    { regular: mdiCheckCircle, outline: mdiCheckCircleOutline },
    { regular: mdiCheck, outline: mdiCheckOutline },
    { regular: mdiBallot, outline: mdiBallotOutline },
    { regular: mdiBatteryCharging100, outline: mdiBatteryChargingOutline },
    { regular: mdiClipboard, outline: mdiClipboardOutline },
    { regular: mdiClipboardCheck, outline: mdiClipboardCheckOutline },
    { regular: mdiClipboardPulse, outline: mdiClipboardPulseOutline },
    { regular: mdiClock, outline: mdiClockOutline },
    { regular: mdiClockAlert, outline: mdiClockAlertOutline },
    { regular: mdiClose, outline: mdiCloseOutline },
    { regular: mdiCloud, outline: mdiCloudOutline },
    { regular: mdiCloudSearch, outline: mdiCloudSearchOutline },
    { regular: mdiCoffee, outline: mdiCoffeeOutline },
    { regular: mdiComment, outline: mdiCommentOutline },
    { regular: mdiCommentAlert, outline: mdiCommentAlertOutline },
    { regular: mdiCommentAccount, outline: mdiCommentAccountOutline },
    { regular: mdiCommentMultiple, outline: mdiCommentMultipleOutline },
    { regular: mdiContentSave, outline: mdiContentSaveOutline },
    { regular: mdiEmail, outline: mdiEmailOutline },
    { regular: mdiEmailOpen, outline: mdiEmailOpenOutline },
    { regular: mdiEmailSearch, outline: mdiEmailSearchOutline },
    { regular: mdiEye, outline: mdiEyeOutline },
    { regular: mdiEyeOff, outline: mdiEyeOffOutline },
    { regular: mdiEngine, outline: mdiEngineOutline },
    { regular: mdiFile, outline: mdiFileOutline },
    { regular: mdiFilter, outline: mdiFilterOutline },
    { regular: mdiFlag, outline: mdiFlagOutline },
    { regular: mdiFlash, outline: mdiFlashOutline },
    { regular: mdiFlask, outline: mdiFlaskOutline },
    { regular: mdiFlaskEmpty, outline: mdiFlaskEmptyOutline },
    { regular: mdiFlowerTulip, outline: mdiFlowerTulipOutline },
    { regular: mdiFolder, outline: mdiFolderOutline },
    { regular: mdiFolderSearch, outline: mdiFolderSearchOutline },
    { regular: mdiForum, outline: mdiForumOutline },
    { regular: mdiHeart, outline: mdiHeartOutline },
    { regular: mdiHome, outline: mdiHomeOutline },
    { regular: mdiKeyboard, outline: mdiKeyboardOutline },
    { regular: mdiLayers, outline: mdiLayersOutline },
    { regular: mdiImage, outline: mdiImageOutline },
    { regular: mdiInformation, outline: mdiInformationOutline },
    { regular: mdiLightbulb, outline: mdiLightbulbOutline },
    { regular: mdiLock, outline: mdiLockOutline },
    { regular: mdiLockOpen, outline: mdiLockOpenOutline },
    { regular: mdiMagnifyPlus, outline: mdiMagnifyPlusOutline },
    { regular: mdiMagnifyMinus, outline: mdiMagnifyMinusOutline },
    { regular: mdiMapMarker, outline: mdiMapMarkerOutline },
    { regular: mdiMap, outline: mdiMapOutline },
    { regular: mdiMapSearch, outline: mdiMapSearchOutline },
    { regular: mdiMicrophone, outline: mdiMicrophoneOutline },
    { regular: mdiNote, outline: mdiNoteOutline },
    { regular: mdiPin, outline: mdiPinOutline }
  ]
}

interface regularOutline {
  regular: string;
  outline: string;
}
